There are 2 ways to check datatypes in R:
1. using typeof() to get R internal datatypes
2. using class() to get datatypes according to OOP R

In [1]:
# a generic integer assignment as we do in other languages
a <- 15
print(a)
print(paste(typeof(a), class(a)))

# a generic float assignment
a <- 15.01
print(a)
print(paste(typeof(a), class(a)))

[1] 15
[1] "double numeric"
[1] 15.01
[1] "double numeric"


In [2]:
# integer assignment in R
a <- 15L
print(a)
print(paste(typeof(a), class(a)))

[1] 15
[1] "integer integer"


In [3]:
# assigning a string
a <- 'This is string data'
print(a)
print(paste(typeof(a), class(a)))

[1] "This is string data"
[1] "character character"


Now let's see what difference does it make when we make a vector using c() and seq()

In [4]:
# creating vectors in R
a <- c(1:12)
print(a)
print(paste(typeof(a), class(a)))

 [1]  1  2  3  4  5  6  7  8  9 10 11 12
[1] "integer integer"


In [5]:
# using sequence to generate vector using defined steps can be integer or float
a <- seq(1,12,2)
print(a)
print(paste(typeof(a), class(a)))

[1]  1  3  5  7  9 11
[1] "double numeric"


In [6]:
# matrix creation in R
a <- matrix(c(1:12), nrow=4, byrow=TRUE)
print(a)
print(paste(typeof(a), class(a)))

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12
[1] "integer matrix"


Wow this is interesting

In [7]:
a <- array(c(1:12), dim=c(3,3))
print(a)
print(paste(typeof(a), class(a)))

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] "integer matrix"


As we saw above typeof() of seq() returns double so let's check it out 

In [8]:
a <- array(seq(1,12,1), dim=c(3,3))
print(a)
print(paste(typeof(a), class(a)))

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] "double matrix"


Let's play with list()

In [9]:
a <- list(13, c(1:12), array(c(2:12), dim=c(3,3)))
print(a)
print(paste(typeof(a), class(a)))

[[1]]
[1] 13

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

[[3]]
     [,1] [,2] [,3]
[1,]    2    5    8
[2,]    3    6    9
[3,]    4    7   10

[1] "list list"


What about boolean values

In [10]:
a <- TRUE
print(a)
print(paste(typeof(a), class(a)))

[1] TRUE
[1] "logical logical"


and factors?

In [11]:
cities <- c('Mumbai', 'Hyderabad')

# without specifying levels
a <- factor(cities)
print(a)
print(paste(typeof(a), class(a)))

# specifying labels
a <- factor(cities, levels=cities)
print(a)
print(paste(typeof(a), class(a)))

#specify labels and pass order as TRUE
a <- factor(cities, order=TRUE, levels=cities)
print(a)
print(paste(typeof(a), class(a)))

[1] Mumbai    Hyderabad
Levels: Hyderabad Mumbai
[1] "integer factor"
[1] Mumbai    Hyderabad
Levels: Mumbai Hyderabad
[1] "integer factor"
[1] Mumbai    Hyderabad
Levels: Mumbai < Hyderabad
[1] "integer ordered" "integer factor" 


Let's checkout dataframes

In [12]:
employee_data <-data.frame(employee_id = c (1:5),
                           employee_name = c("James","Harry","Shinji","Jim","Oliver"),
                           sal = c(642.3,535.2,681.0,739.0,925.26),
                           join_date = as.Date(c("2013-02-04", "2017-06-21", "2012-11-14", "2018-05-19","2016-03-25")),
                           stringsAsFactors = FALSE)
print(employee_data)

  employee_id employee_name    sal  join_date
1           1         James 642.30 2013-02-04
2           2         Harry 535.20 2017-06-21
3           3        Shinji 681.00 2012-11-14
4           4           Jim 739.00 2018-05-19
5           5        Oliver 925.26 2016-03-25


In [13]:
print(paste(typeof(employee_data), class(employee_data)))

[1] "list data.frame"


In [14]:
print(paste(typeof(employee_data$join_date), class(employee_data$join_date)))

[1] "double Date"
